import React, { useState, useCallback } from 'react';
import LoadingSpinner from './components/LoadingSpinner';
import { generateImage } from './services/geminiService';
import ApiKeySelector from './components/ApiKeySelector';
import { GEMINI_IMAGE_MODEL } from './constants';

const App: React.FC = () => {
  const [imagePrompt, setImagePrompt] = useState<string>('');
  const [generatedImageUrl, setGeneratedImageUrl] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [apiKeyReady, setApiKeyReady] = useState<boolean>(false);

  const handleApiKeySelected = useCallback(() => {
    setApiKeyReady(true);
    // You might want to re-check if process.env.API_KEY is actually set here if needed,
    // but per guidelines, we assume success after openSelectKey.
  }, []);

  const handleGenerateImage = useCallback(async () => {
    if (!imagePrompt.trim()) {
      setError('อาจารย์ต้องการคำสั่งที่ชัดเจน! โปรดพิมพ์คำอธิบายภาพ');
      return;
    }
    if (!apiKeyReady) {
      setError('พลังงานยังไม่พร้อม! โปรดตรวจสอบหรือเลือก API Key ก่อน');
      return;
    }

    setIsLoading(true);
    setGeneratedImageUrl(null);
    setError(null);

    try {
      const imageUrl = await generateImage(imagePrompt);
      setGeneratedImageUrl(imageUrl);
    } catch (err: any) {
      console.error('Image generation failed:', err);
      // Check for common API key/model compatibility errors and prompt user to re-select if needed
      if (err.message && err.message.includes("Requested entity was not found")) {
        setError(`พลังงานไม่สมบูรณ์ (API Key มีปัญหาหรือไม่เข้ากันกับโมเดล ${GEMINI_IMAGE_MODEL}) โปรดลองตรวจสอบหรือเลือก API Key ใหม่`);
        if (window.aistudio) { // Only reset selection state if in AI Studio environment
          setApiKeyReady(false);
        }
      } else {
        setError(`อาจารย์พบอุปสรรค: ${err.message || 'เกิดข้อผิดพลาดที่ไม่คาดคิด'}`);
      }
    } finally {
      setIsLoading(false);
    }
  }, [imagePrompt, apiKeyReady]);

  // If the API key is not ready, show the selector component
  if (!apiKeyReady) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-900 text-gray-100 p-4">
        <ApiKeySelector onApiKeySelected={handleApiKeySelected} />
      </div>
    );
  }

  return (
    <div className="min-h-screen flex flex-col items-center p-4 md:p-8 bg-gray-900 text-gray-100 font-sans">
      <h1 className="text-4xl md:text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-500 to-indigo-600 mb-8 text-center drop-shadow-lg">
        อาจารย์สายดำ: จิตรกร AI
      </h1>

      <div className="w-full max-w-3xl bg-gray-800 rounded-xl shadow-2xl p-6 md:p-8 space-y-6 border border-gray-700">
        <div className="flex flex-col">
          <label htmlFor="imagePrompt" className="text-lg font-semibold text-gray-300 mb-2">
            คำสั่งลับของท่าน (Image Prompt):
          </label>
          <textarea
            id="imagePrompt"
            className="w-full p-4 bg-gray-700 border border-gray-600 rounded-lg text-gray-50 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 resize-y min-h-[120px]"
            placeholder="เช่น: 'มังกรบินเหนือภูเขาไฟระเบิดในยามพลบค่ำ, สไตล์แฟนตาซี, รายละเอียดสูง, แสงสีทอง'"
            value={imagePrompt}
            onChange={(e) => setImagePrompt(e.target.value)}
            disabled={isLoading}
          ></textarea>
        </div>

        {error && (
          <div className="p-4 bg-red-800 text-red-100 rounded-lg text-center font-medium">
            {error}
          </div>
        )}

        <button
          onClick={handleGenerateImage}
          className="w-full px-6 py-3 bg-gradient-to-r from-purple-600 to-indigo-700 text-white text-xl font-bold rounded-lg shadow-lg hover:from-purple-700 hover:to-indigo-800 transition duration-300 ease-in-out transform hover:scale-105 disabled:opacity-50 disabled:cursor-not-allowed"
          disabled={isLoading || !imagePrompt.trim()}
        >
          {isLoading ? 'กำลังสร้างสรรค์...' : 'ปลดปล่อยภาพ (Generate Image)'}
        </button>

        <div className="mt-8 pt-6 border-t border-gray-700">
          <h2 className="text-2xl font-bold text-gray-300 mb-4 text-center">ผลงานของอาจารย์:</h2>
          <div className="min-h-[300px] flex items-center justify-center bg-gray-700 rounded-lg overflow-hidden">
            {isLoading && <LoadingSpinner />}
            {!isLoading && generatedImageUrl && (
              <img
                src={generatedImageUrl}
                alt="Generated by AI"
                className="max-w-full h-auto object-contain rounded-lg shadow-md"
              />
            )}
            {!isLoading && !generatedImageUrl && !error && (
              <p className="text-gray-500 italic p-4">ภาพที่ท่านสร้างจะปรากฏที่นี่...</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default App;